m4_define([_OSLC_CHECK_INTERNAL],
AC_BEFORE([AC_PROG_LIBTOOL], [$0])
AC_BEFORE([AM_PROG_LIBTOOL], [$0])
AC_BEFORE([LT_INIT], [$0])
have_oslc=yes
AM_CONDITIONAL([OSLC], [test "$have_oslc" = "yes"])
AC_SUBST([OSLC_CFLAGS])
AC_SUBST([OSLC_LIBS])
)

AC_DEFUN([OSLC_CHECK], [_OSLC_CHECK_INTERNAL([$1])])
